Diversity combining
kit-cel/gnuradio pull request #24
Opened 2018-05-09 09:29 UTC by MoritzLucaSchmid

-Create C++ block diversity_combining_cc with SC and MRC capability.
-Add extensive QA tests.
-Create .xml file for GRC.
-Documentation for Doxygen.

2018-05-09 12:13 UTC, fwunsch requested changes
Looks really, really good so far! I like your coding style very much. I only added some small comments.

Two things crossed my mind: 
1) Wouldn't it be nice to make the combining method settable during runtime? This shouldn't be a major problem and would allow to instantly see the increase or decrease in performance connected to the respective scheme.

2) Have a look at std::valarray. If you are working a lot with vectors, this simplifies point-wise multiplication and other operations commonly required for DSP. This does not mean that I want you to use that everywhere, just have a look at it and decide or discuss if that's helpful for your work.

2018-05-09 12:13 UTC, fwunsch commented on gr-digital/lib/diversity_combiner_cc_impl.cc
> +      const std::string s = "csi";
Why are you doing this in the work function, if it never changes?

2018-05-09 12:13 UTC, fwunsch commented on gr-digital/lib/diversity_combiner_cc_impl.cc
> +      // Handle the samples which are located before the first tag.
This comment should probably be located after this first if clause.

2018-05-09 12:13 UTC, fwunsch commented on gr-digital/lib/diversity_combiner_cc_impl.cc
> +          // Calculated the weighting vector for the next symbol with the received CSI.
Typo in comment

2018-05-09 12:13 UTC, fwunsch commented on gr-digital/lib/diversity_combiner_cc_impl.cc
> +        std::fill(out, &out[length*d_vlen], 0.0);
Why are you using this notation? Just asking. I see why you might want to use std::fill instead of memset (even though I'm unsure about the performance), but you also use memcpy instead of std::copy.

2018-05-09 12:13 UTC, fwunsch commented on gr-digital/lib/diversity_combiner_cc_impl.cc
> +                                               uint16_t offset,
Why are offset and length just uint16_t? 64k is not small, but still in the range an application could get to. Better make this larger.

2018-05-09 12:13 UTC, fwunsch commented on gr-digital/lib/diversity_combiner_cc_impl.cc
> +        process_symbol(input_items, &out[nprocessed*d_vlen], nprocessed*d_vlen, symbol_length);
is nprocessed not always 0 at this point?

2018-05-09 12:13 UTC, fwunsch commented on gr-digital/lib/diversity_combiner_cc_impl.cc
> +          process_symbol(input_items, &out[nprocessed*d_vlen], nprocessed*d_vlen, symbol_length);
again: nprocessed == 0?

2018-05-14 12:09 UTC, MoritzLucaSchmid commented on gr-digital/lib/diversity_combiner_cc_impl.cc
> +        std::fill(out, &out[length*d_vlen], 0.0);
I think memset is not safe for floating point types, while memcpy can be used safely when you pass the proper length in bytes.
But I changed the memcpy now to std::copy to keep the coding style consistent.

2018-05-17 09:50 UTC, MoritzLucaSchmid commented
Thank you @fwunsch for your review!

- [x] The setter method is a great idea! I implemented it.
- [x] The std::valarray is an interesting class template for scientific vector calculation! After looking deeper into it, I decided not to use it. The std::valarray would simplify the code in 3 cases (reduce a for loop to one line of code). The initialization and transfer from the pmt vector to the std::valarray, however, would compensate this improvement. Additionially, the overload of the non-member function  std::begin(std::valarray) seems to be buggy and the code would be an ugly workaround.
- [x] I fixed the minor improvements in the code.

2018-05-18 06:48 UTC, fwunsch approved these changes

2018-05-18 11:05 UTC, merged